### ISSUE TITLE
It can't send links and code on telegram 

### ISSUE THREAD

**Issue by TruthSearchers** [innightwolfsleep/text-generation-webui-telegram_bot#14]
I asked it to send reference link (i can see links in console ) , but it can't send it in telegram (it working perfectly in webui)

Code syntax highlight extension for codes
Also if you can add features of using extensions of  text generation web ui  like sd_picture_api, TTS and send_picture one that would be amazing bro

**Comment by PrincelyDread** [comment]
I realized it burps errors whenever a unusual character is in the response. Works fine on webui though.

**Comment by innightwolfsleep** [comment]
You can add "Code syntax highlight" by  adding in run_server function:
      tg_server.html_tag = ['<pre language="c++">', "</pre>"]
If you want get URLS - this may help:
      tg_server.html_tag = ["", ""]
Write me if it help or not.  


Currently, i use HTML markup for bot message, but it is seems cant processing some symbols properly. Thats a problem during sending links. May be some preprocessing can be added... TBC.

sd api, tts, send picture - currently, this goals is too far

**Comment by TruthSearchers** [comment]
Link still not working and 
Text generation automaticaly stop after colon ':', everytime it got colon it stop generating and after pressing continue it don't generate full output give just a line

**Comment by TruthSearchers** [comment]
Nope links still not working 
Plus i am noticing text generation stop after ':' colon and after press continue it only able to generate a single incomplete line 
So can't see whole code in single message because of it so can't tell if code syntax working

**Comment by innightwolfsleep** [comment]
Added text preprocessing. Some chars (<>#) changes to its html codes. If you know where to find more "broken" symbols - send me please. (^ and % works without replacing)
![2](https://user-images.githubusercontent.com/20921671/234935434-fdbbca13-c242-41f5-90d8-af0141f999f9.PNG)
![1](https://user-images.githubusercontent.com/20921671/234935435-1b0ae786-627f-4078-8198-a4ac58a93e13.PNG)

**Comment by TruthSearchers** [comment]
Here some problems i found just now 
1. It's giving url now but like in a image 
![Screenshot_2023-04-27-22-55-15-53_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/234942297-9f8d9305-7fff-465c-974b-492b7161565f.jpg)

2. Same code thing (it's not generating code in single text message 
![Screenshot_2023-04-27-22-54-21-24_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/234942329-9e57bf1f-7bd4-4fec-8740-a79d966f9dc0.jpg)

3. It's stop generating token (text ) after loading new generation parameters preset as you loaded 
!
![Screenshot_2023-04-27-22-57-08-55_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/234942382-8f9005eb-56ad-4944-85db-fc7c99b1aa04.jpg)

**Comment by innightwolfsleep** [comment]
1) It's giving url now but like in a image
Hmm... what do you see in webui when getting same URL? Bot didnt preprocess URLs, just send like a text. Perhaps, we need more complicated conversion of generated text to HTML... Or may be we can just cut off parse_mode="HTML".

2) Same code thing (it's not generating code in single text message)

I added code to prevent too long generation fo chat mode here:
```
        if self.bot_mode in ["chat", "chat-restricted"]:
            eos_token = '\n'
```
Try to replace eos_token = '\n' on eos_token = None (or eos_token = '')


3) It's stop generating token (text ) after loading new generation parameters preset as you loaded
Just fixed.

**Comment by TruthSearchers** [comment]
No problem now 
Btw bro are you planning for discord bot too?

**Comment by innightwolfsleep** [comment]
There is atready one discord bot:
https://github.com/ChobPT/text-generation-webui-discord_bot

**Comment by TruthSearchers** [comment]
Actually that on webhook can only give output can't take input haha

I was adding TTS and sd_api_pic in telegram bot just like web ui

**Comment by innightwolfsleep** [comment]
I was adding TTS and sd_api_pic telegram bot just like web ui
>>> If you already added this functions to text-generation-webui-telegram_bot - send pull request)

**Comment by TruthSearchers** [comment]
Definitely gonna tell you when i completed ☺️

**Comment by TruthSearchers** [comment]
Hey bro 
You should also update it to latest web ui like end of turn replaced by turn_template

**Comment by innightwolfsleep** [comment]
I have an idea with prefix... Like # is impersonate, - or $ can be replacing order prefix.

**Comment by TruthSearchers** [comment]
That's cool bro i like it , it will be more easy 
 you also have to update params 

'end_of_turn' to 'turn_template'  according to latest ooobaboga update for more accurate responses

**Comment by TruthSearchers** [comment]
Hey there @innightwolfsleep got the new error hehe 
When i change mode to chat from admin  it giving me Attribute error  (changing it in telegram_config.cfg)
"AttributeError : 'TelegramBotWrapper' object has no attribute 'admin_list' " 

Also i noticed some wierd replies like last when i use telegram bot , it give me replies same to it , but now when i ask hey there , it says who are you, or write article it say i will write then i tap continue - topic change (did you changed the parameters?)
Its working fine with older version giving perfect replies (older version)

**Comment by innightwolfsleep** [comment]
> some wierd replies like last when i use telegram bot , it give me replies same to it , but now when i ask hey there , it says who are you, or write article it say i will write then i tap continue - topic change (did you changed the parameters?)
> Its working fine with older versi

Added

**Comment by innightwolfsleep** [comment]
> Hey there @innightwolfsleep got the new error hehe When i change mode to chat from admin it giving me Attribute error (changing it in telegram_config.cfg) "AttributeError : 'TelegramBotWrapper' object has no attribute 'admin_list' "

fixed

**Comment by innightwolfsleep** [comment]
> Also i noticed some wierd replies like last when i use telegram bot , it give me replies same to it , but now when i ask hey there , it says who are you, or write article it say i will write then i tap continue - topic change (did you changed the parameters?) Its working fine with older version giving perfect replies (older version)

Hm... I made bunch of commits during and rework structure this holiday, so it is not easy to find problem. Can you send me "perfect" variant of script or link to last "perfect" commit?

I have tested bot just now, but didnt find a problem. Perhaps it was problem with erased "context", it is just solved.

**Comment by TruthSearchers** [comment]
Sure i will help gonna test the new commit , will let you know all errors

**Comment by TruthSearchers** [comment]
That problem still occuring here the screen shot 
**Old response** 
![Screenshot_2023-05-01-14-27-33-63_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/235433850-2c6c1ae3-f9eb-4da1-8fd1-9703143fea7e.jpg)
![Screenshot_2023-05-01-14-49-25-05_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/235434085-db2aa6a0-c35f-48ac-8583-8cbc471c805c.jpg)


 **new response coming (3 screenshots ) after the update you done yesterday**
![Screenshot_2023-05-01-14-27-21-51_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/235433886-97f02e5f-5018-4a22-a705-ec616b2dbd28.jpg)
![Screenshot_2023-05-01-14-32-05-72_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/235433890-84de4c17-6076-4663-b61f-c3f51cb8cac7.jpg)
![Screenshot_2023-05-01-14-46-26-54_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/40608534/235433892-86818f56-4304-49ee-a8ee-5260d53d52bb.jpg)

**Comment by TruthSearchers** [comment]
One more problem after pressing continue its giving output out of topic like this 
![Uploading Screenshot_2023-05-01-14-59-48-94_948cd9899890cbd5c2798760b2b95377.jpg…]()

**Comment by innightwolfsleep** [comment]
Hm... I spent about three hours to find simple answer - need to add space after "{Char}:" 
![image](https://user-images.githubusercontent.com/20921671/235496893-be4b7052-2724-4009-8bd6-f2d69c7aa68f.png)

**Comment by TruthSearchers** [comment]
Thanks @innightwolfsleep bro ,sorry i made you work hard on it. But it was cooool i loved the telegram bot 
Gonna check the new updated code

**Comment by innightwolfsleep** [comment]
SileroTTS added. 
Cant reuse silero stright from ooba, so it is not need to acticvate silero extension.
